version: "3.8"
services:
  webserver:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - dev_env_network

  app:
    build:
      context: ./app
    deploy:
      replicas: 10
      resources:
        limits:
          cpus: "0.15"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 256M
    expose:
      - "3000-3010"
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - db
    networks:
      - dev_env_network

  db:
    image: mongo
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 256M
    environment:
      MONGO_URI: mongodb+srv://camilotello:Tello123@cluster0.eprzlvc.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      JWT_SECRET: Tello123
    networks:
      - dev_env_network

networks:
  dev_env_network:
    driver: bridge